### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/data-broker#110]
Memory is allocated
https://github.com/IBM/data-broker/blob/5271f74482fa5334dc2f5b13f861b4421f08bdb8/backend/transports/double_buffer.c#L44
Potential leak of memory pointed to by 'buffer '
https://github.com/IBM/data-broker/blob/5271f74482fa5334dc2f5b13f861b4421f08bdb8/backend/transports/double_buffer.c#L50

**Comment by lasch** [comment]
Thanks for the report. Appreciated. I'll look into it.

**Comment by lasch** [comment]
I checked the code and it's correct that there's is a bug in that function. However, it's not a memory leak since the allocated memory is correctly freed by calling dbBE_Transport_dbuffer_free().

The actual problem is that there is no check for the failed malloc in line 44. This in turn would cause a segfault in line 46, when buffer is dereferenced. A fix and PR are in progress.

**Comment by lasch** [comment]
fix merged. Will close issue. Please re-open if you think it's not addressed properly.
